k8sImageRegistry: quay.io
hwameistorImageRegistry: ghcr.io

scheduler:
  replicas: 1
  kubeApiServerConfigFilePath: /etc/kubernetes/admin.conf
  imageRepository: hwameistor/scheduler
  tag: v0.1.2
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi

localDiskManager:
  tolerationsOnMaster: true
  imageRepository: hwameistor/local-disk-manager
  tag: v0.0.2
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi

localStorage:
  tolerationsOnMaster: true
  registrar:
    imageRepository: k8scsi/csi-node-driver-registrar
    tag: v1.1.0
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 5m
        memory: 5Mi
  member:
    imageRepository: hwameistor/local-storage
    tag: v0.1.6
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 5m
        memory: 5Mi

localStorageCSIController:
  replicas: 1
  provisioner:
    imageRepository: k8scsi/csi-provisioner
    tag: v2.0.3
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 5m
        memory: 5Mi
  attacher:
    imageRepository: k8scsi/csi-attacher
    tag: v3.0.1
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 5m
        memory: 5Mi
  resizer:
    imageRepository: k8scsi/csi-resizer
    tag: v1.0.1
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 5m
        memory: 5Mi
