apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hwameistor-ldm-controller
  namespace: {{ .Release.Namespace}} 
  labels:
    control-plane: hwameistor-ldm-controller
spec:
  selector:
    matchLabels:
      control-plane: hwameistor-ldm-controller
  template:
    metadata:
      labels:
        control-plane: hwameistor-ldm-controller
    spec:
      securityContext:
        runAsNonRoot: false
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: {{ .Values.ldmImage}}
        name: manager
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        securityContext:
          privileged: true
          capabilities:
            add: [ "SYS_ADMIN" ]
          allowPrivilegeEscalation: true
        volumeMounts:
          - name: udev
            mountPath: /run/udev
          - name: procmount
            mountPath: /host/proc
            readOnly: true
          - name: devmount
            mountPath: /dev
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: {{ .Values.ldmResources.limits.cpu}}
            memory: {{ .Values.ldmResources.limits.memory}}
          requests:
            cpu: {{ .Values.ldmResources.requests.cpu}}
            memory: {{ .Values.ldmResources.requests.memory}}
      serviceAccountName: hwameistor-admin 
      serviceAccount: hwameistor-admin
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        operator: Exists
      volumes:
        - name: udev
          hostPath:
            path: /run/udev
            type: Directory
        - name: procmount
          # mount /proc/1/mounts (mount file of process 1 of host) inside container
          # to read which partition is mounted on / path
          hostPath:
            path: /proc
            type: Directory
        - name: devmount
          # the /dev directory is mounted so that we have access to the devices that
          # are connected at runtime of the pod.
          hostPath:
            path: /dev
            type: Directory
      terminationGracePeriodSeconds: 10
