{{- if not (lookup "v1" "ConfigMap" .Release.Namespace "hwameistor-scheduler-config") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: hwameistor-scheduler-config
  namespace: {{ .Release.Namespace}}
data:
apiVersion: v1
kind: ConfigMap
metadata:
  name: hwameistor-scheduler-config
  namespace: {{ .Release.Namespace }}
data:
{{- if (semverCompare "> 1.20-0" (include "hwameistor.kubeVersion" .)) }}
  hwameistor-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: hwameistor-scheduler
        plugins:
          filter:
            enabled:
            - name: hwameistor-scheduler-plugin
          reserve:
            enabled:
            - name: hwameistor-scheduler-plugin
    leaderElection:
      leaderElect: true
      resourceName: hwameistor-scheduler
    clientConnection:
      kubeconfig: /etc/kubernetes/scheduler.conf 
{{- else }}
  hwameistor-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: hwameistor-scheduler
    leaderElection:
      leaderElect: true
      lockObjectName: hwameistor-scheduler
      resourceLock: leases
    plugins:
      filter:
        enabled:
          - name: hwameistor-scheduler-plugin
      reserve:
        enabled:
          - name: hwameistor-scheduler-plugin
      unreserve:
        enabled:
          - name: hwameistor-scheduler-plugin
{{- end -}}
{{- end }}
